name: socketire
author: Alexander Ewetumo<trinoxf@gmail.com>
version: 0.0.6
homepage: http://github.com/influx6/socketire.dart
description: A simple collection of client and server side websocket wrapper
dependencies:
  browser: any
  ds: any
  guardedfs: any
  hub: any
  path: any
  streamable: any
