name: socketire
version: 0.0.1
author: Alexander Ewetumo<trinoxf@gmail.com>
description: A simple collection of client and server side websocket wrapper
homepage: http://github.com/influx6/socketire.dart
dependencies:
  ds: any
  hub: any
  invocable: any
  statemanager: any
  streamable: any
  browser: any

